[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
swap = "9vtrwv4Y7ZmLEDHmgxnGJqF5oAb35298u1e8VsDA2ZRi"

[programs.devnet]
swap = "9vtrwv4Y7ZmLEDHmgxnGJqF5oAb35298u1e8VsDA2ZRi"

[programs.mainnet]
swap = "9vtrwv4Y7ZmLEDHmgxnGJqF5oAb35298u1e8VsDA2ZRi"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = ".keys/feePayerPrivateKey.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[workspace]
types = "app/idl/"